# JDBC properties for MSSQL
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=member_mygo;encrypt=false;trustServerCertificate=true
spring.datasource.username=Guest
spring.datasource.password=zgmfx10A!

# Hibernate dialect for MSSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Enable Hibernate ddl-auto (optional: use create-drop or validate if needed)
spring.jpa.hibernate.ddl-auto=update

# Enable SQL logging for debugging
logging.level.org.springframework.jdbc.core=TRACE
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

